### ISSUE TITLE
How to use this with lsp-mode?

### ISSUE THREAD

**Issue by gtusr** [dmille56/powershell-ts-mode#5]
Can you provide instructions on how to configure `powershell-ts-mode` to work with lsp-mode's `pwsh-ls` powershell language server?

**Comment by dmille56** [comment]
Hmm there shouldn't be any conflicts that I know of between the two modes (don't think there should be much overlap as the scope of the two projects are different) though I haven't tested.  If there's anything needed to be done for configuration feel free to share so we can update the docs.

**Comment by gtusr** [comment]
`lsp-mode` is now configured by default to activate itself for `powershell-ts-mode`
